sonar.projectKey=laravel-first-project
sonar.projectName=Laravel Project

sonar.organization=amine1919a
sonar.host.url=https://sonarcloud.io

sonar.token=78ed5572e9b479e5540dff23b5e9b59697b198a0

sonar.sources=app,routes,resources
sonar.tests=tests
sonar.sourceEncoding=UTF-8